'use client';
import { useEffect, useRef, useState } from 'react';
import { Loader2, Mail, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { removeCachedPdfsExcept } from '@/lib/pdf-cache';
import { fetchStoreAuthMenus, fetchStoreAuthSession, requestStoreOtp, searchStoreAuthStores, StoreAuthMenu, StoreAuthSession, verifyStoreOtp } from '@/lib/supabase-api';
const DEVICE_KEY = 'insou-store-device-id';
function deviceId() { try { const old = localStorage.getItem(DEVICE_KEY); if (old) return old; const id = crypto.randomUUID(); localStorage.setItem(DEVICE_KEY, id); return id; } catch { return crypto.randomUUID(); } }
export function StoreOtpLogin({ onAuthenticated }: { onAuthenticated: (session: StoreAuthSession, menus: StoreAuthMenu[]) => Promise<void> }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<Array<{ id:string; code:string; name:string; area:string }>>([]); const [selected, setSelected] = useState<typeof results[number]>();
  const [step, setStep] = useState<'search'|'confirm'|'otp'>('search'); const [challengeId, setChallengeId] = useState(''); const [otp, setOtp] = useState(''); const [cooldown, setCooldown] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const resumed = useRef(false);
  const offline = typeof navigator !== 'undefined' && !navigator.onLine;
  useEffect(() => { if (resumed.current || offline) return; resumed.current = true; void (async () => { const session = await fetchStoreAuthSession(); if (session.authenticated && session.store) { const data = await fetchStoreAuthMenus(); await onAuthenticated(session, data.menus); } else if (session.clearCache) await removeCachedPdfsExcept([]); })().catch(() => undefined); }, [offline, onAuthenticated]);
  useEffect(() => { if (!cooldown) return; const timer = window.setInterval(() => setCooldown(v => Math.max(0, v - 1)), 1000); return () => window.clearInterval(timer); }, [cooldown]);
  useEffect(() => { const value = query.trim(); if (step !== 'search' || value.length < 2) { setResults([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { void searchStoreAuthStores(value, controller.signal).then(setResults).catch(() => { if (!controller.signal.aborted) setError('店舗情報を取得できませんでした'); }); }, 300); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query, step]);
  const choose = (store: typeof results[number]) => { setSelected(store); setStep('confirm'); setError(''); };
  const send = async () => { if (!selected || offline) return; setLoading(true); setError(''); try { const data = await requestStoreOtp({ storeId: selected.id, deviceId: deviceId() }); setChallengeId(data.challengeId); setStep('otp'); setCooldown(30); } catch { setError('認証コードを送信できませんでした。しばらくしてから再試行してください。'); } finally { setLoading(false); } };
  const verify = async () => { if (!selected || otp.length !== 6 || offline) return; setLoading(true); setError(''); try { await verifyStoreOtp({ challengeId, otp, deviceId: deviceId(), deviceName: '店舗タブレット' }); const session = await fetchStoreAuthSession(); if (!session.authenticated || !session.store) throw new Error('session'); const data = await fetchStoreAuthMenus(); await onAuthenticated(session, data.menus); } catch { setError('認証コードを確認できませんでした。再発行してやり直してください。'); } finally { setLoading(false); } };
  return <main className="grid min-h-svh place-items-center bg-[#f4f7fb] p-5"><section className="w-full max-w-xl rounded-3xl bg-white p-7 shadow-xl sm:p-10"><div className="mb-7 flex items-center gap-3"><div className="grid size-12 place-items-center rounded-2xl bg-blue-600 text-white"><Mail /></div><div><p className="font-serif text-2xl font-bold text-slate-900">INSOU</p><p className="text-xs tracking-[0.2em] text-slate-400">STORE MENU</p></div></div><h1 className="text-2xl font-bold text-slate-900">店舗ログイン</h1><p className="mt-2 text-sm text-slate-500">店舗メールで認証し、メニューを表示します。</p>{offline && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">オンライン接続が必要です。通信を確認してください。</p>}{step === 'search' && <><label className="mt-7 block text-sm font-bold text-slate-700">店舗名</label><div className="relative mt-2"><Search className="absolute left-3 top-3.5 size-5 text-slate-400" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="店舗名を2文字以上入力" className="h-12 pl-10 text-base" disabled={offline} /></div>{results.length > 0 && <div className="mt-3 space-y-2">{results.map(store => <button key={store.id} onClick={() => choose(store)} className="w-full rounded-xl border p-4 text-left hover:border-blue-500"><span className="font-bold">{store.name}</span><span className="ml-2 text-sm text-slate-500">{store.area}</span></button>)}</div>}</>}{step === 'confirm' && selected && <div className="mt-7 rounded-2xl bg-slate-50 p-5"><p className="font-bold text-slate-900">{selected.name}で認証します</p><p className="mt-2 text-sm text-slate-600">登録済みの店舗メールアドレスへ確認コードを送信します。</p><div className="mt-5 flex gap-3"><Button variant="outline" onClick={() => setStep('search')}>店舗を選び直す</Button><Button onClick={() => void send()} disabled={loading || offline}>{loading && <Loader2 className="mr-2 size-4 animate-spin" />}送信する</Button></div></div>}{step === 'otp' && <div className="mt-7"><p className="font-bold text-slate-900">確認コードを入力</p><p className="mt-2 text-sm text-slate-600">メールに記載された6桁のコードを入力してください。</p><Input className="mt-4 h-14 text-center text-2xl tracking-[0.5em]" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))} /><Button className="mt-4 h-12 w-full" onClick={() => void verify()} disabled={loading || otp.length !== 6 || offline}>{loading && <Loader2 className="mr-2 size-4 animate-spin" />}認証する</Button><Button variant="ghost" className="mt-2 w-full" onClick={() => void send()} disabled={loading || cooldown > 0 || offline}>{cooldown > 0 ? `再送信（${cooldown}秒後）` : '認証コードを再送信'}</Button></div>}{error && <p className="mt-5 text-sm font-semibold text-red-600">{error}</p>}</section></main>;
}
